name: argopy-binder
channels:
  - conda-forge
dependencies:
  - python=3.8.5
  - python-dateutil=2.8.1
  - numpy=1.18.5
  - scipy=1.4.1
  - pandas=1.0.4
  - matplotlib=3.3.2
  - scikit-learn=0.23.2
  - ipython=7.20.0
  - netcdf4=1.5.4
  - seaborn=0.11.1
  - gsw=3.4.0
  - pip=20.3.3
  - cartopy=0.18.0
  - pip
  - pip:
    - argopy
